GOOGLE_CALENDAR_API_KEY: AIzaSyA4jgwxzxIZ-IeelQawFbCCWudL5l9WzYo
NSCS_Calendar_ID: 'tamu.edu_lkjcimlfp2qgv12vqhhoqdnk28@group.calendar.google.com'

S3_BUCKET: '431public'
AWS_ACCESS_KEY_ID: 'AKIAILMJ6JNCNH2ER4YQ'
AWS_SECRET_ACCESS_KEY: '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'
